apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
    - name: source
  params:
    - name: url
      description: Git repository URL
      type: string
    - name: revision
      description: Git revision to clone
      type: string
      default: main
  steps:
    - name: clone
      image: alpine/git
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        git clone -b $(params.revision) $(params.url) .